import { existsSync } from "node:fs";
import { mkdir, readdir } from "node:fs/promises";
import { join } from "node:path";

// Draws the README's banner and one card per extension in the icons' hand-drawn world (ink on paper,
// Kalam lettering, Twitch purple), then lists the cards in README.md. The SVGs embed Kalam, since
// GitHub shows them as images that load no outside fonts, and fill their own paper, so they read
// the same on light and dark themes.

const root = join(import.meta.dir, "..");
const outDir = join(root, ".github", "readme");

const INK = "#18181b";
const PAPER = "#fffdf5";
const TWITCH = "#9146ff";
const WIDTH = 880;
// A card's text fits between its icon and its doodle; past these, shorten the name or description.
const TITLE_CHARS = 21;
const TAGLINE_CHARS = 36;
const TAGLINE_LINES = 3;
// The banner's shelf, clear of its subtitle.
const SHELF_START = 590;
const SHELF_END = WIDTH - 30;

interface Extension {
  name: string;
  title: string;
  description: string;
  icon: string;
  doodle: string | undefined;
}

async function fontFace(weight: number): Promise<string> {
  const path = Bun.resolveSync(`@fontsource/kalam/files/kalam-latin-${weight}-normal.woff2`, root);
  const data = Buffer.from(await Bun.file(path).arrayBuffer()).toString("base64");
  return `@font-face{font-family:Kalam;font-weight:${weight};src:url(data:font/woff2;base64,${data}) format("woff2")}`;
}

const style = `<style>${await fontFace(400)}${await fontFace(700)}text{font-family:Kalam,"Comic Sans MS",cursive}</style>`;

/** Escapes text for XML and HTML, attribute values included. */
function escape(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

/**
 * Inlines an SVG file's drawing, prefixing its ids so several can share one document. Attributes on
 * the file's root `<svg>` other than `viewBox` are dropped, so draw with attributes on its children.
 */
function inline(svg: string, prefix: string, x: number, y: number, size: [number, number]): string {
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error(`An SVG to inline for ${prefix} lacks a viewBox.`);
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replaceAll(/\bid="([^"]+)"/g, `id="${prefix}-$1"`)
    .replaceAll(/\bhref="#([^"]+)"/g, `href="#${prefix}-$1"`)
    .replaceAll(/url\(#([^)]+)\)/g, `url(#${prefix}-$1)`);
  return `<svg x="${x}" y="${y}" width="${size[0]}" height="${size[1]}" viewBox="${viewBox}">${body}</svg>`;
}

function wrap(text: string, width: number): string[] {
  const lines: string[] = [];
  for (const word of text.trim().split(/\s+/)) {
    const last = lines.at(-1);
    if (last !== undefined && `${last} ${word}`.length <= width)
      lines[lines.length - 1] = `${last} ${word}`;
    else lines.push(word);
  }
  return lines;
}

/** A purple squiggle under a title of roughly `width` px, like the popups' `title-squiggle`. */
function squiggle(x: number, y: number, width: number): string {
  const step = width / 4;
  return `<path d="M${x} ${y}c${step / 2} -5 ${step} 3 ${step} 0s${step} -4 ${step * 2} 0s${step / 2} 4 ${step} 0" fill="none" stroke="${TWITCH}" stroke-width="4" stroke-linecap="round"/>`;
}

function frame(height: number, body: string, label: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${height}" viewBox="0 0 ${WIDTH} ${height}" role="img" aria-label="${escape(label)}">
<!-- Generated by scripts/readme.ts; edit that script or the extension's assets, then run \`bun run readme\`. -->
${style}
<defs><filter id="wobble" x="-5%" y="-10%" width="110%" height="120%"><feTurbulence type="fractalNoise" baseFrequency=".035" numOctaves="2" seed="3"/><feDisplacementMap in="SourceGraphic" scale="4"/></filter></defs>
<rect x="10" y="10" width="${WIDTH - 20}" height="${height - 20}" rx="24" fill="${PAPER}" stroke="${INK}" stroke-width="3" filter="url(#wobble)"/>
${body}
</svg>
`;
}

function card(extension: Extension): string {
  const lines = wrap(extension.description, TAGLINE_CHARS);
  if (extension.title.length > TITLE_CHARS) {
    throw new Error(
      `${extension.title} is too long a name for its card (${TITLE_CHARS} characters).`,
    );
  }
  if (lines.length > TAGLINE_LINES || lines.some((line) => line.length > TAGLINE_CHARS)) {
    throw new Error(
      `${extension.name}'s description is too long for its card (${TAGLINE_LINES} lines of ${TAGLINE_CHARS} characters).`,
    );
  }
  const tagline = lines
    .map(
      (line, index) =>
        `<text x="200" y="${146 + index * 30}" font-size="22" fill="${INK}" opacity=".75">${escape(line)}</text>`,
    )
    .join("");
  const doodle = extension.doodle
    ? inline(extension.doodle, `${extension.name}-doodle`, 596, 31, [260, 170])
    : "";
  return frame(
    232,
    `${inline(extension.icon, `${extension.name}-icon`, 44, 52, [128, 128])}
<text x="200" y="96" font-size="38" font-weight="700" fill="${INK}">${escape(extension.title)}</text>
${squiggle(200, 112, extension.title.length * 18)}
${tagline}
${doodle}`,
    `${extension.title}: ${extension.description}`,
  );
}

function banner(extensions: Extension[]): string {
  // The extensions' TVs stand on a shelf, with a dashed one waiting for the next; more TVs shrink
  // to share the shelf.
  const step = Math.min(92, (SHELF_END - SHELF_START) / (extensions.length + 1));
  const size = step - 12;
  const top = 196 - size;
  const tilts = [-4, 3, -2, 4];
  const shelf = extensions
    .map((extension, index) => {
      const x = SHELF_START + index * step;
      const tilt = tilts[index % tilts.length];
      return `<g transform="rotate(${tilt} ${x + size / 2} ${top + size / 2})">${inline(extension.icon, `${extension.name}-shelf`, x, top, [size, size])}</g>`;
    })
    .join("");
  const next = SHELF_START + extensions.length * step;
  // The dashed TV's box and antennas, in the icon's 128 px proportions.
  const unit = size / 128;
  return frame(
    250,
    `<text x="48" y="112" font-size="56" font-weight="700" fill="${INK}">chrome-extensions</text>
${squiggle(48, 130, 470)}
<text x="50" y="170" font-size="24" fill="${INK}" opacity=".75">Personal Chrome extensions, one TV at a time.</text>
<text x="50" y="204" font-size="18" fill="${INK}" opacity=".55">WXT · React · Tailwind CSS · shadcn/ui · Bun</text>
${shelf}
<g fill="none" stroke="${INK}" stroke-width="3" stroke-linecap="round" filter="url(#wobble)">
  <g opacity=".45">
    <rect x="${next + 12 * unit}" y="${top + 24 * unit}" width="${105 * unit}" height="${93 * unit}" rx="${18 * unit}" stroke-dasharray="7 8"/>
    <path d="M${next + 62 * unit} ${top + 24 * unit}l${-14 * unit} ${-16 * unit}M${next + 66 * unit} ${top + 24 * unit}l${14 * unit} ${-16 * unit}"/>
  </g>
  <path d="M${SHELF_START - 20} 206C${SHELF_START + 80} 202 760 203 ${SHELF_END} 205" stroke-width="4"/>
</g>
<text x="${next + 64 * unit}" y="${top + 82 * unit}" font-size="${36 * unit}" font-weight="700" fill="${INK}" text-anchor="middle" opacity=".45">?</text>`,
    "chrome-extensions: personal Chrome extensions, one TV at a time.",
  );
}

function titleCase(name: string): string {
  return name.replaceAll(
    /(^|-)(\w)/g,
    (_, dash: string, letter: string) => `${dash ? " " : ""}${letter.toUpperCase()}`,
  );
}

const extensionsDir = join(root, "extensions");
const extensions: Extension[] = [];
for (const entry of await readdir(extensionsDir, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const dir = join(extensionsDir, entry.name);
  if (!existsSync(join(dir, "package.json"))) continue;
  const { description, name } = (await Bun.file(join(dir, "package.json")).json()) as {
    description: string;
    name: string;
  };
  const iconPath = join(dir, "assets", "icon.svg");
  if (!existsSync(iconPath)) throw new Error(`${name} needs a 128 px icon at ${iconPath}.`);
  const doodlePath = join(dir, "assets", "readme-doodle.svg");
  extensions.push({
    description,
    doodle: existsSync(doodlePath) ? await Bun.file(doodlePath).text() : undefined,
    icon: await Bun.file(iconPath).text(),
    name,
    title: titleCase(name),
  });
}
extensions.sort((a, b) => a.name.localeCompare(b.name));

const readmePath = join(root, "README.md");
const readme = await Bun.file(readmePath).text();
const list = extensions
  .map(
    (extension) =>
      `<a href="extensions/${extension.name}"><img src=".github/readme/${extension.name}.svg" alt="${escape(`${extension.title}: ${extension.description}`)}" width="880"></a>`,
  )
  .join("\n\n");
const marked = /(<!-- extensions:start -->)[\s\S]*?(<!-- extensions:end -->)/;
if (!marked.test(readme))
  throw new Error("README.md lacks the <!-- extensions:start/end --> markers.");

await mkdir(outDir, { recursive: true });
await Bun.write(join(outDir, "banner.svg"), banner(extensions));
for (const extension of extensions) {
  await Bun.write(join(outDir, `${extension.name}.svg`), card(extension));
}
// A replacer function, so a `$` in a description is never read as a replacement pattern.
await Bun.write(
  readmePath,
  readme.replace(marked, (_, start: string, end: string) => `${start}\n\n${list}\n\n${end}`),
);
console.log(`Drew the banner and ${extensions.length} cards, and listed them in README.md.`);
